_base_: ${resolve_pkg_path:aiaccel.torch.apps.config}/train_ddp.yaml

n_gpus: 8
walltime: "16:0:0"

sr: 16000
n_fft: 512
hop_length: 128

n_mic: 4
n_src: 3
dim_latent: 50

trainer:
  max_epochs: 200
  gradient_clip_val: 5.0
  sync_batchnorm: True
  
  benchmark: True
  use_distributed_sampler: False

  precision: bf16-mixed

  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      filename: "{epoch:04d}"
      save_last: True
    - _target_: lightning.pytorch.callbacks.RichProgressBar
      refresh_rate: 5
    - _target_: lightning.pytorch.callbacks.RichModelSummary
      max_depth: 3

    - _target_: sbss.common.callbacks.CyclicAnnealerCallback
      name: beta
      cycle: 10
      max_value: 1.0
      ini_period: 50
      ini_max_value: 10.0

    - _target_: sbss.nfca.callbacks.PsdVisualizerCallback
    - _target_: sbss.nfca.callbacks.XtVisualizerCallback

hdf5_prefix: ${working_directory}/../../../hdf5/unsupervised.derev_64000
datamodule:
  _target_: aiaccel.torch.lightning.datamodules.SingleDataModule
  train_dataset_fn:
    _partial_: True
    _target_: sbss.common.datasets.WavHDF5Dataset
    dataset_path: ${hdf5_prefix}.tr.hdf5
    grp_list: ${hdf5_prefix}.tr.json

  val_dataset_fn:
    _partial_: True
    _target_: sbss.common.datasets.WavHDF5Dataset
    dataset_path: ${hdf5_prefix}.cv.hdf5
    grp_list: ${hdf5_prefix}.cv.json

  common_args:
    randperm_mic: True

  batch_size: ${eval:"128 // ${n_gpus}"}
  num_workers: 12

task:
  _target_: sbss.nfca.tasks.JdAviTask
  n_fft: ${n_fft}
  hop_length: ${hop_length}
  n_src: ${n_src}
  beta: 1.0

  encoder:
    _target_: sbss.nfca.encoders.JdUNetEncoder
    n_fft: ${n_fft}
    n_mic: ${n_mic}
    n_src: ${n_src}
    dim_latent: ${dim_latent}

    diagonalizer:
      _target_: sbss.common.diagonalizers.iss_diagonalizer.ISSDiagonalizer
      norm_q: True

  decoder:
    _target_: sbss.nfca.decoders.ResDecoder
    n_fft: ${n_fft}
    dim_latent: ${dim_latent}

  optimizer_config:
    _target_: aiaccel.torch.lightning.OptimizerConfig
    optimizer_generator:
      _partial_: True
      _target_: torch.optim.Adam
      lr: 1.e-3