_base_: ../base_config.yaml

walltime: "16:0:0"

task:
  encoder:
    _target_: sbss.nfca.encoders.DilcnvEncoder
    n_fft: ${n_fft}
    n_mic: ${n_mic}
    n_src: ${n_src}
    dim_latent: ${dim_latent}